# Generated by Django 4.2.7 on 2023-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_mood_alter_journal_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(),
        ),
    ]
